---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    cluster-api.cattle.io/rancher-auto-import: "true"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: observability
  namespace: observability
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: observability
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: observability
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: observability
  namespace: observability
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.22.1
    values: |
      exportKubeConfig:
        additionalSecrets:
          - name: observability-kubeconfig
            namespace: observability
