---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: observability
  namespace: observability
  labels:
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: observability
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: observability
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: observability
  namespace: observability
spec:
  controlPlaneEndpoint:
    host: "suseai.observability.svc"
    port: 443
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.22.1
    values: |-
      controlPlane:
        proxy:
          extraSANs:
          - suseai.observability.svc
        service:
          spec:
            type: NodePort
